name: Build and Test

on:
  pull_request:
    branches:
      - main
      
jobs:

  test:
    name: Run on MacOS
    runs-on: macos-12

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: XCode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'

      - name: Bundle install
        run: bundle install

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Swiftgen
        run: brew install swiftgen

      - name: Install lizard
        run: pip install lizard
        
      - name: Install Sonar scanner
        run: brew install sonar-scanner

      - name: Build and test
        run: |
          bundle exec fastlane test \
          sonar_login:"$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}